name: Test API (Python)

on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: descargar código
              uses: actions/checkout@v3

            - name: Configurar Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Instalar dependencias
              run: |
                python -m pip install --upgrade pip
                pip install -r ApiCandyModularizada-main-segura-main/requirements.txt

            - name: ejecutar pruebas
              run: |
                pytest tests/test1.py
    